// pack-csv.ts — the Discovery Pack as a 3-section CSV (Master Register +
// Retention Matrix + Data Risk Register), so the download mirrors the screen.
//
// Shared by the client (instant download) and /api/template-download (the
// emailed attachment). The server builds its own copy from the taxonomy —
// it never accepts CSV text from the browser, so the attachment can only
// ever contain our own content.

import type { DiscoveryRegister } from "./register";

/**
 * One quoted CSV cell. A leading = + - @ (or tab/CR) makes Excel and Sheets
 * evaluate the cell as a formula; prefixing a quote keeps it as plain text.
 */
export function csvCell(v: unknown): string {
  let s = String(v ?? "");
  if (/^[=+\-@\t\r]/.test(s)) s = "'" + s;
  return `"${s.replace(/"/g, '""')}"`;
}

const row = (cells: unknown[]) => cells.map(csvCell).join(",");

export function buildPackCsv(reg: DiscoveryRegister, nicheName: string): string {
  const lines: string[] = [
    `# DPDPA Personal Data Discovery Pack — ${nicheName} — generated by SaralPrivacy`,
    `# ${reg.counts.items} items · ${reg.counts.categories} categories · ${reg.counts.highRisk} high-risk · Suggested — validate before adoption. Not legal advice.`,
    "",
    "# 1. Master Personal Data Register",
    row(["Data item", "Description", "Principal", "Category", "Purpose", "Collection source", "Stored at", "Risk", "Risk reason", "Recommended action", "External recipients", "Status"]),
  ];
  for (const r of reg.rows)
    lines.push(row([r.dataItem, r.description, r.dataPrincipal, r.dataCategory, r.purpose, r.collectionSource, r.storedAt, r.riskLevel, r.riskReason, r.recommendedAction, r.externalRecipients.join("; "), r.status]));
  lines.push("", "# 2. Retention Matrix (Suggested — validate before adoption)",
    row(["Category", "Trigger (clock starts)", "As per DPDPA", "As per other law", "Other-law citation", "Status", "Disposal", "Systems affected"]));
  for (const r of reg.retention)
    lines.push(row([r.dataItem, r.retentionTrigger, r.dpdpaBaseline, r.otherLaw?.period ?? "None identified — erase when purpose served", r.otherLaw?.citation ?? "", r.status === "statutory_floor" ? "Statutory floor" : "You determine", r.disposalMethod, r.systemsAffected.join("; ")]));
  lines.push("", "# 3. Data Risk Register",
    row(["Risk", "Severity", "Priority", "Category", "Affected data", "Location / flow", "Reason", "Recommended control", "Suggested mapping question", "Mapping priority"]));
  for (const r of reg.risks)
    lines.push(row([r.risk, r.severity, r.priority, r.category, r.affectedData.join("; "), r.locationOrFlow, r.reason, r.recommendedControl, r.suggestedMappingQuestion, r.mappingPriority]));
  return lines.join("\r\n");
}
