-- 0001_initial_schema.sql — Appwrite → Supabase migration (spec: SUPABASE_MIGRATION_SPEC.md §3)
-- GENERATED by tools/migrate-supabase/generate-ddl.ts from schema-report.json
-- (live Appwrite introspection 2026-09-02T13:03:00.975Z). Do not hand-edit tables;
-- regenerate instead.
--
-- Posture: RLS enabled on every table with NO policies (deny-all) — only the
-- service-role key reads/writes until Blueprint P3 introduces real auth.

create schema if not exists ops;   -- marketing/ops surface
create schema if not exists app;   -- product surface

create extension if not exists pgcrypto with schema extensions;

-- UUIDv7 (time-ordered): no pg_uuidv7 extension on this platform, so define
-- the standard overlay construction over gen_random_uuid().
create or replace function ops.uuid_generate_v7() returns uuid
language sql volatile parallel safe as $$
  select encode(
    set_bit(set_bit(
      overlay(uuid_send(gen_random_uuid())
        placing substring(int8send((extract(epoch from clock_timestamp())*1000)::bigint) from 3)
        from 1 for 6),
      52, 1), 53, 1), 'hex')::uuid
$$;


-- ── leads → ops.leads ─────────────────────────────────────
create table ops.leads (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  company text not null,
  industry text,
  company_size text,
  source text not null,
  issue_summary text,
  preferred_contact text,
  preferred_time text,
  consent_version text,
  risk_level text,
  created_at_attr timestamptz,
  ip_address text,
  city text,
  country text,
  region text
);
alter table ops.leads enable row level security;

-- ── subscribers → ops.subscribers ───────────────────────────────
create table ops.subscribers (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  email text not null,
  industry text,
  frequency text,
  consent_version text,
  user_agent text,
  created_at_attr timestamptz,
  ip_address text,
  city text,
  country text,
  region text,
  consent_source text not null check (consent_source in ('manual', 'assessment_form', 'intro_email_one_click', 'report_email_cta', 'admin_added')),
  consent_timestamp timestamptz,
  unsubscribe_token text,
  status text not null check (status in ('active', 'unsubscribed', 'bounced', 'complained')),
  unsubscribed_at timestamptz
);
alter table ops.subscribers enable row level security;
create unique index ix_subscribers_unsub_token_unique on ops.subscribers (unsubscribe_token);
create index ix_subscribers_sub_status_idx on ops.subscribers (status);

-- ── downloads → ops.downloads ─────────────────────────────────
create table ops.downloads (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  email text not null,
  company text not null,
  industry text,
  company_size text,
  consent_email boolean,
  consent_phone boolean,
  consent_webinars boolean,
  privacy_version text,
  downloaded_at timestamptz,
  ip_address text,
  city text,
  country text,
  region text,
  phone text,
  language text
);
alter table ops.downloads enable row level security;

-- ── assessments → app.assessments ───────────────────────────────
create table app.assessments (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  email text not null,
  industry text not null,
  risk_level text not null,
  applicability_score double precision,
  maturity_score double precision,
  risk_score double precision,
  urgency_score double precision,
  overall_score double precision,
  created_at_attr timestamptz,
  ip_address text,
  city text,
  country text,
  region text,
  raw_score bigint,
  final_score bigint,
  data_exposure bigint,
  control_maturity bigint,
  operational_readiness bigint,
  consent_report boolean,
  consent_newsletter boolean,
  consent_followup boolean,
  verdict_band text,
  report_type text,
  name text,
  business_name text,
  mobile text,
  q11_blocker text,
  q12_resource text,
  red_flags_json text,
  immediate_actions_json text,
  thirty_day_actions_json text,
  report_token text,
  report_token_expires_at text,
  answers_json text,
  category_scores_json text,
  email_sent_at text,
  email_sent_by text
);
alter table app.assessments enable row level security;

-- ── briefings → app.briefings_meta ────────────────────────────
create table app.briefings_meta (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  title text not null,
  slug text not null,
  summary text,
  why_it_matters text,
  action_checklist text,
  status text,
  approval_token text,
  scheduled_for timestamptz,
  sent_at timestamptz,
  created_at_attr timestamptz,
  subscriber_count bigint,
  excerpt text,
  category text,
  tags text,
  industries text,
  author text,
  published_at text,
  read_time bigint,
  featured boolean,
  infographic_base64 text,
  outreach_used_at timestamptz
);
alter table app.briefings_meta enable row level security;
create index ix_briefings_meta_slug_idx on app.briefings_meta (slug);

-- ── consent_log → ops.consent_log ───────────────────────────────
create table ops.consent_log (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  email text not null,
  name text,
  source text not null,
  consent_type text not null,
  privacy_version text not null,
  ip_address text,
  user_agent text,
  city text,
  country text,
  region text,
  timestamp text not null,
  withdrawn_at text,
  consent_value boolean not null
);
alter table ops.consent_log enable row level security;

-- ── survey_responses → ops.survey_responses ──────────────────────────
create table ops.survey_responses (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  role text,
  employee_size text,
  sector text,
  operating_footprint text,
  state_ut text,
  city text,
  digital_personal_data text,
  data_types text,
  data_storage text,
  controls_in_place text,
  readiness_self_view text,
  biggest_blocker text,
  most_helpful_resource text,
  score_band text,
  name text,
  business_name text,
  work_email text,
  mobile_number text,
  contact_preference text,
  consent_version text,
  consent_timestamp text,
  created_at_attr text,
  score bigint,
  wants_report boolean,
  consent_followup boolean,
  consent_given boolean
);
alter table ops.survey_responses enable row level security;

-- ── blog_posts → ops.blog_posts ────────────────────────────────
create table ops.blog_posts (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  title text not null,
  slug text not null,
  excerpt text not null,
  lane text not null,
  author text not null,
  tags text,
  industries text,
  validated_at text,
  published_at text,
  section_what_changed text,
  status text,
  section_law_says text,
  read_time bigint,
  score_legal_accuracy bigint,
  score_primary_source bigint,
  score_currency bigint,
  score_scope bigint,
  score_operational bigint,
  validation_score bigint,
  featured boolean,
  sections_json text,
  infographic_url text
);
alter table ops.blog_posts enable row level security;

-- ── blogger_accounts → ops.blogger_accounts ──────────────────────────
create table ops.blogger_accounts (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  email text not null,
  name text not null,
  bio text,
  password_hash text,
  active boolean,
  invite_token text,
  token_expires text,
  created_at_attr text
);
alter table ops.blogger_accounts enable row level security;

-- ── template_downloads → ops.template_downloads ────────────────────────
create table ops.template_downloads (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  business_name text not null,
  employees text,
  phone text not null,
  email text,
  template_name text,
  consent_contact boolean,
  report_token text,
  ip_address text,
  city text,
  country text,
  created_at_attr text,
  contact_name text not null,
  source text
);
alter table ops.template_downloads enable row level security;

-- ── outreach_contacts → ops.outreach_contacts ─────────────────────────
create table ops.outreach_contacts (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  email text not null,
  name text,
  company text,
  industry text,
  source text,
  status text not null check (status in ('pending', 'sent', 'subscribed', 'bounced', 'unsubscribed', 'complained', 'failed')),
  intro_sent_at timestamptz,
  subscribed_at timestamptz,
  magic_token text not null,
  created_at_attr timestamptz not null
);
alter table ops.outreach_contacts enable row level security;
create unique index ix_outreach_contacts_email_unique on ops.outreach_contacts (email);
create unique index ix_outreach_contacts_magic_token_unique on ops.outreach_contacts (magic_token);
create index ix_outreach_contacts_status_idx on ops.outreach_contacts (status);
create index ix_outreach_contacts_created_idx on ops.outreach_contacts (created_at_attr);

-- ── email_send_log → ops.email_send_log ────────────────────────────
create table ops.email_send_log (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  recipient_email text not null,
  email_type text not null check (email_type in ('intro', 'briefing_daily', 'briefing_weekly', 'report', 'subscribe_confirmation', 'unsubscribe_confirmation')),
  briefing_id text,
  resend_message_id text,
  status text not null check (status in ('sent', 'delivered', 'opened', 'clicked', 'bounced', 'complained')),
  consent_basis text not null,
  sent_at timestamptz not null,
  updated_at_attr timestamptz
);
alter table ops.email_send_log enable row level security;
create index ix_email_send_log_recipient_idx on ops.email_send_log (recipient_email);
create index ix_email_send_log_type_idx on ops.email_send_log (email_type);
create index ix_email_send_log_sent_at_idx on ops.email_send_log (sent_at);
create index ix_email_send_log_resend_msg_idx on ops.email_send_log (resend_message_id);

-- ── ai_citations → ops.ai_citations ──────────────────────────────
create table ops.ai_citations (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  run_id text not null,
  date text not null,
  week_num bigint not null,
  engine text not null,
  engine_label text not null,
  query_id text not null,
  query_text text not null,
  cited text not null,
  position bigint,
  cited_page text,
  quote_type text,
  competitors text,
  raw_citations text,
  content_snippet text,
  duration_ms bigint,
  error_message text
);
alter table ops.ai_citations enable row level security;
create index ix_ai_citations_idx_run_id on ops.ai_citations (run_id);
create index ix_ai_citations_idx_date on ops.ai_citations (date);
create index ix_ai_citations_idx_engine on ops.ai_citations (engine);

-- ── notice_captures → app.notice_captures ───────────────────────────
create table app.notice_captures (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  email text not null,
  name text,
  business_name text,
  sector text,
  readiness_score bigint,
  export_type text,
  source text,
  consent boolean,
  ip_address text,
  city text,
  country text,
  created_at_attr text
);
alter table app.notice_captures enable row level security;
create index ix_notice_captures_idx_created on app.notice_captures (created_at);
create index ix_notice_captures_idx_sector on app.notice_captures (sector);
create index ix_notice_captures_idx_source on app.notice_captures (source);

-- ── notice_runs (absent in Appwrite; shape from code/spec) → app.notice_runs
create table app.notice_runs (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  payload jsonb
);
alter table app.notice_runs enable row level security;

-- ── notice_events → app.notice_events ─────────────────────────────
create table app.notice_events (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  session_id text,
  payload text,
  created_at_attr text
);
alter table app.notice_events enable row level security;
create index ix_notice_events_idx_created on app.notice_events (created_at);
create index ix_notice_events_idx_name on app.notice_events (name);

-- ── business_profiles (absent in Appwrite; shape from code/spec) → app.business_profiles
create table app.business_profiles (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  payload jsonb
);
alter table app.business_profiles enable row level security;

-- ── dsar_requests (absent in Appwrite; shape from code/spec) → app.dsar_requests
create table app.dsar_requests (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  payload jsonb
);
alter table app.dsar_requests enable row level security;

-- ── chat_feedback (absent in Appwrite; shape from code/spec) → ops.chat_feedback
create table ops.chat_feedback (
  id uuid primary key default ops.uuid_generate_v7(),
  legacy_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  "sessionId" text not null,
  "turnId" text not null,
  helpful boolean,
  reason text,
  "pageUrl" text,
  "failureKind" text,
  "redactedQuestion" text,
  ts timestamptz
);
alter table ops.chat_feedback enable row level security;


-- Deny-all hardening: nothing for anon/authenticated until P3.
revoke all on all tables in schema ops from anon, authenticated;
revoke all on all tables in schema app from anon, authenticated;
alter default privileges in schema ops revoke all on tables from anon, authenticated;
alter default privileges in schema app revoke all on tables from anon, authenticated;
